# Generated by Django 5.2 on 2026-01-17 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'db_table': 'city',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AirQuality',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('aqi', models.SmallIntegerField(help_text='Air Quality Index')),
                ('pm25', models.FloatField(help_text='PM2.5 concentration')),
                ('pm10', models.FloatField(help_text='PM10 concentration')),
                ('no2', models.FloatField(help_text='NO2 concentration')),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='air_quality_logs', to='api.city')),
            ],
            options={
                'db_table': 'air_quality',
                'managed': True,
                'indexes': [models.Index(fields=['city', 'date'], name='air_quality_city_id_736fbc_idx')],
                'unique_together': {('city', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AgricultureData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('crop_type', models.CharField(help_text='Name of the crop (e.g., Wheat, Rice)', max_length=50)),
                ('yield_amount', models.FloatField(db_column='yield', help_text='Yield in ton/ha')),
                ('soil_moisture', models.FloatField(help_text='Soil moisture percentage')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agriculture_logs', to='api.city')),
            ],
            options={
                'db_table': 'agriculture_data',
                'managed': True,
                'indexes': [models.Index(fields=['city', 'date'], name='agriculture_city_id_0f954c_idx')],
                'unique_together': {('city', 'date', 'crop_type')},
            },
        ),
        migrations.CreateModel(
            name='HealthIndex',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('health_risk_score', models.FloatField(help_text='Risk score 0-100')),
                ('risk_level', models.CharField(help_text='Low / Medium / High', max_length=10)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_logs', to='api.city')),
            ],
            options={
                'db_table': 'health_index',
                'managed': True,
                'indexes': [models.Index(fields=['city', 'date'], name='health_inde_city_id_04a413_idx')],
                'unique_together': {('city', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TrafficData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('traffic_density', models.SmallIntegerField(help_text='Congestion level (1-10)')),
                ('avg_speed', models.FloatField(help_text='Average vehicle speed in km/h')),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_logs', to='api.city')),
            ],
            options={
                'db_table': 'traffic_data',
                'managed': True,
                'indexes': [models.Index(fields=['city', 'date'], name='traffic_dat_city_id_48ee64_idx')],
                'unique_together': {('city', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('temperature', models.FloatField(help_text='Temperature in Celsius')),
                ('humidity', models.FloatField(help_text='Humidity percentage')),
                ('rainfall', models.FloatField(help_text='Rainfall in mm')),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_logs', to='api.city')),
            ],
            options={
                'db_table': 'weather_data',
                'managed': True,
                'indexes': [models.Index(fields=['city', 'date'], name='weather_dat_city_id_efb374_idx')],
                'unique_together': {('city', 'date')},
            },
        ),
    ]
