# Generated by Django 5.2 on 2026-01-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='ingested_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
